import * as React from 'react';
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '@mui/material/Button'
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import TextField from '@mui/material/TextField';
import Select from '@mui/material/Select';
import Box from '@mui/material/Box';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [operator, setOperator] = React.useState('addition');

  const handleChange = (event) => {
    setoperator(event.target.value);
  };

  return (
    <>
      <Head>
        <title>Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Container maxWidth="sm">
          <Box sx={{ my: 4 }}>
            <Typography variant="h4" component="h1" gutterBottom>
              Calculadora
            </Typography>
            <TextField id="outlined-basic" label="Operador 1" variant="outlined" />
            <TextField id="outlined-basic" label="Operador 2" variant="outlined" />
            <FormControl fullWidth>
              <InputLabel id="demo-simple-select-label">Operacion</InputLabel>
              <Select
                labelId="demo-simple-select-label"
                id="demo-simple-select"
                value={operator}
                label="Operacion"
                onChange={handleChange}
              >
                <MenuItem value={'addition'}>Addition</MenuItem>
                <MenuItem value={'subtraction'}>Subtraction</MenuItem>
                <MenuItem value={'multiplication'}>Multiplication</MenuItem>
                <MenuItem value={'division'}>Division</MenuItem>
                <MenuItem value={'square_root'}>Square root</MenuItem>
                <MenuItem value={'random_string'}>Random Strings</MenuItem>
              </Select>
            </FormControl>
            <Button variant="contained">Calcular</Button>
            <TextField
              id="outlined-multiline-static"
              label="Multiline"
              multiline
              rows={4}
              defaultValue="Aca veras los resultados"
            />
          </Box>
        </Container>
      </main>
    </>
  )
}
